#!/usr/bin/env python3
"""Regenerate the ablation table from result files.

The README's table is a build artifact. It is never edited by hand, so it
cannot drift from what the harness measured -- which is the property that
makes the numbers worth reading at all.

Usage:
    python scripts/build_ablation_table.py [--results DIR] [--baseline FILE]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from evals.report import compare_runs  # noqa: E402
from evals.runner import RunResult  # noqa: E402

COLUMNS = [
    ("ndcg@10", "nDCG@10", True),
    ("recall@10", "Recall@10", True),
    ("groundedness", "Grounded %", True),
    ("false_refusal", "False refusal", False),
    ("latency_ms", "p50 ms", False),
    ("cost_usd", "$/query", False),
]


def fmt(value: float | None, metric: str) -> str:
    if value is None:
        return "—"
    if metric == "latency_ms":
        return f"{value:.0f}" if value >= 10 else f"{value:.2f}"
    if metric == "cost_usd":
        return f"{value:.5f}"
    if metric in ("groundedness", "false_refusal"):
        return f"{value:.1%}"
    return f"{value:.4f}"


def delta_cell(delta: float | None, significant: bool, higher_is_better: bool) -> str:
    """Render a delta, marking whether it survived the paired bootstrap.

    An unmarked delta is one the eval set cannot distinguish from noise. That
    distinction is the whole reason the column exists -- without it the table
    invites you to keep changes that did nothing.
    """
    if delta is None:
        return ""
    arrow = "" if significant else " (ns)"
    return f"{delta:+.4f}{arrow}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", default="evals/results")
    parser.add_argument("--baseline", default="evals/baselines/main.json")
    parser.add_argument("--out", default=None, help="write Markdown here instead of stdout")
    args = parser.parse_args()

    result_dir = Path(args.results)
    files = sorted(result_dir.glob("*.json"))
    if not files:
        print(f"no result files in {result_dir}", file=sys.stderr)
        return 1

    runs = [RunResult.load(f) for f in files]
    runs.sort(key=lambda r: r.provenance.get("created_at", ""))

    baseline_path = Path(args.baseline)
    baseline = RunResult.load(baseline_path) if baseline_path.exists() else None

    header = (
        "| Configuration | " + " | ".join(label for _, label, _ in COLUMNS) + " | vs baseline |"
    )
    divider = "|" + "---|" * (len(COLUMNS) + 2)
    lines = [header, divider]

    for run in runs:
        label = run.config.get("label") or run.config["system"]["name"]
        cells = [label]
        for metric, _, _ in COLUMNS:
            agg = run.aggregates.get(metric)
            cells.append(fmt(agg["mean"] if agg else None, metric))

        verdict = "baseline"
        if baseline is not None and run.run_id != baseline.run_id:
            try:
                comparisons = compare_runs(baseline, run, metrics=["ndcg@10"])
            except ValueError:
                verdict = "n/a (different dataset)"
            else:
                cmp = comparisons.get("ndcg@10")
                verdict = delta_cell(cmp.delta, cmp.significant, True) if cmp else "n/a"
        cells.append(verdict)
        lines.append("| " + " | ".join(cells) + " |")

    lines.append("")
    lines.append(
        "_(ns) marks a delta whose 95% paired-bootstrap confidence interval includes "
        "zero: not distinguishable from noise on this eval set._"
    )
    lines.append("")
    lines.append(f"_Generated by `scripts/build_ablation_table.py` from {len(runs)} run(s)._")

    table = "\n".join(lines)
    if args.out:
        Path(args.out).write_text(table + "\n", encoding="utf-8")
        print(f"written to {args.out}")
    else:
        print(table)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
